#
# Example PlatformIO configuration file for SSL and non-SSL builds.
#
# Before you will be able to build the SSL version of this project, you will
# need to explicitly install the espressif8266_stage platform.
#
# To perform this installation, refer to step 1 of:
# http://docs.platformio.org/en/latest/platforms/espressif8266.html#using-arduino-framework-with-staging-version

[platformio]
default_envs = sonoffmini_switch

[common]
build_flags =
  -DEMMDBG_LEVEL=EMMDBG_NONE

[env]
framework = arduino
lib_deps = 
	../../
monitor_speed = 115200

[env:sonoffmini_switch]
platform = espressif8266@~1.6.0
board = esp8285
upload_protocol = esptool
build_flags =
	${common.build_flags}
	-DFIRMWARE_ID=0x6701
	-DBUTTON=4
	-DSTATUS_LED=13
	-DBUTTON0_MODE=TOGGLE
	-DRELAY0GPIO=12
	-DRELAY0ONVAL=1

##########################################################################
# płytka z aliexpress 
# wymiary 80mm x 50mm x 20mm
# lista pinów (nazwy na płytce przy pinach)
#1.  GND: power ground
#2.  Relay: IO5 jest domyślnie używany. Jeśli chcesz użyć innego IO do napędzania przekaźnika, możesz usunąć R14, a następnie podłączyć I/O przekaźnika napędu do tego sworznia przekaźnika
#3.  IO2: GPIO2: UARTI-TXD; Blue LED on esp8266 module
#4.  IO4: GPIO4
#5.  RX: UARTO-RXD: GPIO3
#6.  3V3: zasilanie 3.3V
#7.  SCLK: zegar
#8.  IO15: GPIO15: MTDO; HSPICS; UARTO-RTS
#9.  IO0: GPIO0
#10. IO5: GPIO5
#11. TX: UARTO-TXD; GPIO1
#12. 5V: zasilanie 5V
#13. IO10: GPIO10
#14. MISO: wyjście Slave i wejście hosta
#15. IO13: GPIO13; HSPI-MOSI; UARTO-CTS
#16. IO14: GPIO14; HSPI-CLK
#17. ADC: wynik konwersji A/D. Zakres napięcia wejściowego: 0 ~ 1V, zakres wartości: 0 ~ 1024
#18. 3V3: zasilanie 3.3V
#19. MOSI: wyjście hosta i wejście slave
#20. IO9: GPIO9  (NIE UŻYWAĆ!)
#21. CSO: wybór układu
#22. IO12: GPIO12; HSPI-MISO
#23. IO16: GPIO16; programmable LED)
#24. GND: power ground
[env:esp12frelayx1v12_relay]
platform = espressif8266@~1.6.0
board = esp12e
upload_protocol = esptool
build_flags =
	${common.build_flags}
	-DFIRMWARE_ID=0x6803
	-DHAS_DS18B20=1
	-DDS18B20=4
	-DBUTTON=15
	-DBUTTON0_MODE=TOGGLE
	-DRELAY0GPIO=05
	-DRELAY0ONVAL=1
	-DRELAY1GPIO=02
	-DRELAY1ONVAL=0
	-DRELAY2GPIO=10
	-DRELAY2ONVAL=0
	-DRELAY3GPIO=12
	-DRELAY3ONVAL=0
	-DRELAY4GPIO=13
	-DRELAY4ONVAL=0
	-DRELAY5GPIO=14
	-DRELAY5ONVAL=0
	-DTEMPMIN=30.00
	-DTEMPMAX=40.00
	-DSTATUS_LED=16

[env:esp12frelayx1v12_heater]
platform = espressif8266@~1.6.0
board = esp12e
upload_protocol = esptool
build_flags =
	${common.build_flags}
	-DFIRMWARE_ID=0x6802
	-DHAS_DS18B20=1
	-DDS18B20=4
	-DBUTTON=15
	-DBUTTON0_MODE=TOGGLE
	-DRELAY0GPIO=05
	-DRELAY0ONVAL=1
	-DRELAY1GPIO=02
	-DRELAY1ONVAL=0
	-DSTATUS_LED=16

[env:esp12frelayx1v12_heater2]
platform = espressif8266@~1.6.0
board = esp12e
upload_protocol = esptool
build_flags =
	${common.build_flags}
	-DFIRMWARE_ID=0x6803
	-DHAS_DS18B20=1
	-DDS18B20=5
	-DBUTTON=15
	-DBUTTON0_MODE=TOGGLE
	-DRELAY0GPIO=02
	-DRELAY0ONVAL=0
	-DRELAY1GPIO=04
	-DRELAY1ONVAL=0
	-DSTATUS_LED=16
